import Link from "next/link";import {config} from "@/lib/config";
/* eslint-disable @next/next/no-img-element */
const H=({t,s}:{t:string;s?:string})=><div className="mb-8"><h2 className="font-serif text-4xl md:text-5xl">{t}</h2>{s&&<p className="mt-2 text-mute">{s}</p>}</div>;
const W=({children}:{children:React.ReactNode})=><section className="mx-auto max-w-[1440px] px-5 pt-20">{children}</section>;
const ig=[1,2,3,4,5,6,7,8];
export function InstagramStrip(){return <W><H t="AS SEEN ON @MRIDUL_BY_MR" s="Discover the latest sarees, colours and styling inspiration from the MRIDUL world."/>
 <div className="-mx-5 flex snap-x gap-3 overflow-x-auto px-5 pb-2">{ig.map(i=><a key={i} href={config.instagram} target="_blank" rel="noopener" aria-label="View on Instagram" className="w-40 shrink-0 snap-start md:w-56"><img src={`/img/p${i}-${i%2+1}.svg`} alt="" className="aspect-square w-full object-cover"/></a>)}</div></W>}
export function Community(){return <W><H t="REAL DRAPES. REAL MRIDUL." s="See how the MRIDUL community wears their favourite sarees."/>
 <div className="grid grid-cols-2 gap-2 md:grid-cols-3 md:gap-4">{[3,1,6,2,8,5].map((i,k)=><img key={k} src={`/img/p${i}-2.svg`} alt="" className="aspect-square w-full object-cover"/>)}</div>
 <a href={config.instagram} target="_blank" rel="noopener" className="btn mt-6">FOLLOW @MRIDUL_BY_MR →</a></W>}
export function FollowStory(){return <section className="mt-20 bg-ink px-5 py-16 text-center text-cream"><h2 className="font-serif text-4xl md:text-5xl">FOLLOW THE MRIDUL STORY</h2><p className="mt-2">@mridul_by_mr</p><p className="mx-auto my-4 max-w-md text-sm opacity-80">New drops, restocks, colours and styling inspiration — straight from our Instagram.</p><a href={config.instagram} target="_blank" rel="noopener" className="btn-o !border-cream text-cream hover:!bg-cream hover:!text-ink">FOLLOW ON INSTAGRAM →</a></section>}
export function Mood(){const m=[["EVERYDAY","Easy. Comfortable. Effortless."],["OFFICE","Polished enough for work. Comfortable enough for all day."],["FESTIVE","Colour and detail for celebrations."],["SPECIAL OCCASIONS","Beautiful drapes for moments worth dressing up for."]];
 return <W><H t="FIND YOUR MRIDUL"/><div className="grid grid-cols-2 gap-3 md:grid-cols-4 md:gap-4">{m.map(([t,d],i)=><Link key={t} href="/shop" className="group relative block aspect-[3/4] overflow-hidden"><img src={`/img/p${i*2+1}-1.svg`} alt="" className="h-full w-full object-cover transition-transform duration-[1500ms] group-hover:scale-105"/><div className="absolute inset-0 flex flex-col justify-end bg-gradient-to-t from-ink/70 to-transparent p-3 text-cream md:p-5"><h3 className="font-serif text-xl md:text-2xl">{t}</h3><p className="text-xs">{d}</p></div></Link>)}</div></W>}
export function Fabric(){const f=[["120-COUNT MUL COTTON","Our signature fabric featured across several MRIDUL collections."],["LIGHTWEIGHT FEEL","Comfortable and easy to wear."],["BEAUTIFUL DRAPE","A soft base designed for an effortless fall."],["DETAIL-LED DESIGN","Floral details, scalloped borders, embroidery and tassels add character."]];
 return <W><H t="FEEL THE DIFFERENCE"/><div className="grid gap-px border border-line bg-line sm:grid-cols-2 lg:grid-cols-4">{f.map(([t,d])=><div key={t} className="bg-cream p-6 md:p-8"><h3 className="font-serif text-2xl">{t}</h3><p className="mt-2 text-sm text-mute">{d}</p></div>)}</div></W>}
export function Journal(){const a=[["HOW TO STYLE A MUL COTTON SAREE","Simple ways to style your favourite Mul Cotton saree from everyday looks to special occasions."],["FIND YOUR PERFECT SAREE COLOUR","From soft pastels to statement shades, discover a colour that feels like you."],["THE DETAILS THAT MAKE A SAREE","A closer look at floral details, scalloped borders, embroidery and tassels."]];
 return <W><H t="THE MRIDUL JOURNAL" s="Sarees, styling and stories."/><div className="grid gap-8 md:grid-cols-3">{a.map(([t,d],i)=><article key={t}><img src={`/img/p${i*3+2}-1.svg`} alt="" className="aspect-[4/3] w-full object-cover"/><h3 className="mt-4 font-serif text-2xl">{t}</h3><p className="mt-2 text-sm text-mute">{d}</p><Link href="/shop" className="mt-3 inline-block text-xs tracking-widest underline">READ MORE →</Link></article>)}</div></W>}
export function Benefits(){const b=[["BEAUTIFUL FABRICS","Thoughtfully selected fabrics for comfortable dressing."],["EXPRESSIVE COLOURS","Beautiful shades to suit different moods and occasions."],["DISTINCTIVE DETAILS","From floral motifs to borders, embroidery and tassels."],["EASY SUPPORT","Need help choosing? Talk to us directly."]];
 return <W><H t="WHY MRIDUL"/><div className="grid grid-cols-2 gap-6 md:grid-cols-4">{b.map(([t,d])=><div key={t}><h3 className="text-xs tracking-widest">{t}</h3><p className="mt-2 text-sm text-mute">{d}</p></div>)}</div></W>}
